---
title: "Mathematische Grundlagen der (Wirtschafts-)Informatik"
header-includes:
  - "\\usepackage{systeme}"
---

```{r setup, include=FALSE}
# .aux Dateien vom LaTeX-Übersetzungsprozess löschen? 
options(tinytex.clean = FALSE)

# ---------------------------------------------------------------------------
# Einige Funktionen und Variabeln sind in die Datei 'prelude.R' ausgelagert.
# Diese werden hier nachgeladen und angepasst.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
source("prelude.R")
initPrelude(
    TRUE           # Soll geprüft werden ob alle Pakete installiert sind?
)

# ---------------------------------------------------------------------------
```

```{r localKnitrButtonSetup, eval=!RENDEREDBYSCRIPT, echo=FALSE, include=FALSE}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Einstellungen für den Fall, dass man den knitr-Button nutzt. Sonst bitte
# 'eval=FALSE' einstellen!
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if (!exists("prelude.rendertools")) {
    loadPrelude("prelude_rendertools.R")
}

privateVorstellung <<- TRUE   # Zeige die Private Vorstellung

UseCache <<- FALSE

createPrivateYaml(
    "Dipl.-Math. Norman Markgraf",  # Dozent*innenname
    "WS 2020/21",                   # Semesterkennzeichen
    "Münster/Düsseldorf"            # Studienort(e)
)

# Erzeuge Skript "DozentenSkript", "StudierendenSkript" oder "LösungsSkript": 
makeSkriptOfType("DozentenSkript") 
```

```{r ggplot2Setup, eval=TRUE, echo=FALSE, include=FALSE}
library(ggplot2)

# ggformula, also ggplot2 muss noch etwas konfiguriert werden.
theme_set(
  theme_classic(22.44)
)
```

```{r setUpChildren, eval=TRUE, include=FALSE}
## Liste aller Teilskripte, die in das Skript integriert werden sollen.
childrenToInclude <- c(
    "Organisatorisches", 
    "Hinweise", 
    "Mengenlehre", 
    "Relationen", 
    "Kombinatorik", 
    "Logik", 
    "Finanzmathematik", 
    "Differenzialrechnung",
    "LineareAlgebra"
)

## Für einen Testlauf einzelner Teilskripte einfach diesen Abschnitt
## auf TRUE setzen und nur die Teilskripte einfügen, die benötigt werden.
if (FALSE) {
  childrenToInclude <- c(
    "LineareAlgebra"
  )
  # Zur Sicherheit die private Vorstellung NICHT in das Testlauf-Skript!
  privateVorstellung <<- FALSE
}

## Funktion, die auswertet ob ein Teilskript eingesetzt werden soll oder nicht.
includeChild <- function(name, children=childrenToInclude, all=FALSE) {
    all | (name %in% children)
}
```

```{r child = './Inhalte/MGWI-Organisatorisches.Rmd', eval = includeChild("Organisatorisches")}
```

```{r child = './private/private-Vorstellung.Rmd', eval = privateVorstellung}
```

```{r child = './Inhalte/Organisatorisches/MGWI-Hinweise.Rmd', eval = includeChild("Hinweise")}
```

```{r child = './Inhalte/MGWI/Mengenlehre.Rmd', eval = includeChild("Mengenlehre")}
```

```{r child = './Inhalte/MGWI/Relationen.Rmd', eval = includeChild("Relationen")}
```

```{r child = './Inhalte/MGWI/Kombinatorik.Rmd', eval = includeChild("Kombinatorik")}
```

```{r child = "./Inhalte/MGWI/Logik.Rmd", eval = includeChild("Logik")}
```

```{r child = "./Inhalte/MGWI/LineareAlgebra.Rmd", eval = includeChild("LineareAlgebra")}
```

```{r child = "./Inhalte/MGWI/Differenzialrechnung.Rmd", eval = includeChild("Differenzialrechnung")}
```

```{r child = "./Inhalte/MGWI/Finanzmathematik.Rmd", eval = includeChild("Finanzmathematik")}
```



```{r finalize, include=FALSE}
# ---------------------------------------------------------------------------
# Setzt einige Parameter zurück.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
finalizePrelude()
```
